# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(max_length=225)),
                ('title', models.CharField(blank=True, choices=[(0, 'yesintent'), (1, 'nointent'), (2, 'letschatintent'), (3, 'chatintent')], max_length=225)),
                ('base_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('correctly_responded', models.BooleanField()),
                ('correct_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_intent', to='chat.Intent')),
                ('guessed_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guessed_intent', to='chat.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_id', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('conversation', models.ManyToManyField(to='chat.Conversation')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.User'),
        ),
        migrations.AddField(
            model_name='response',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Session'),
        ),
        migrations.AddField(
            model_name='query',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Response'),
        ),
        migrations.AddField(
            model_name='query',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Session'),
        ),
        migrations.AddField(
            model_name='query',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.User'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='query',
            field=models.ManyToManyField(to='chat.Query'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='response',
            field=models.ManyToManyField(to='chat.Response'),
        ),
    ]
