# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170411_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conversation',
            field=models.ManyToManyField(blank=True, to='chat.Conversation'),
        ),
    ]
