# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170411_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='intent',
            name='title',
            field=models.IntegerField(blank=True, choices=[(0, 'yesintent'), (1, 'nointent'), (2, 'letschatintent'), (3, 'chatintent')]),
        ),
    ]
