# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20170411_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='query',
        ),
        migrations.RemoveField(
            model_name='query',
            name='response',
        ),
        migrations.RemoveField(
            model_name='user',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='chat.User'),
        ),
        migrations.AddField(
            model_name='query',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation'),
        ),
        migrations.AddField(
            model_name='response',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Query'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='First', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Last', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='intent',
            name='title',
            field=models.CharField(blank=True, choices=[('yesintent', 'yesintent'), ('nointent', 'nointent'), ('letschatintent', 'letschatintent'), ('chatintent', 'chatintent')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='correct_intent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_intent', to='chat.Intent'),
        ),
        migrations.AlterField(
            model_name='query',
            name='correctly_responded',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='guessed_intent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guessed_intent', to='chat.Intent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
