# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20170411_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='response',
        ),
    ]
