# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_conversation_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'Querie'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.User'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='title',
            field=models.CharField(blank=True, choices=[('yesintent', 'yesintent'), ('nointent', 'nointent'), ('letschatintent', 'letschatintent'), ('chatintent', 'chatintent')], max_length=50, unique=True),
        ),
    ]
