# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import dojo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(help_text='Markdown 문법을 써주세요.')),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('lnglat', models.CharField(help_text='경도, 위도 포맷으로 입력', max_length=50, validators=[dojo.models.lnglat_validator])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=10)),
            ],
        ),
    ]
