# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.IntegerField(default=10),
        ),
    ]
