# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_auto_20170405_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[(0, '과학'), (1, '경제'), (2, '정치')], max_length=100),
        ),
    ]
