# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_auto_20170412_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdraw')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdraw')], max_length=100),
        ),
    ]
