# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0009_auto_20170412_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='name',
            field=models.CharField(default='unknown 기자', max_length=20, verbose_name='이름'),
        ),
    ]
